const vfile = require('to-vfile')
const report = require('vfile-reporter')
const unified = require('unified')
const markdown = require('remark-parse')
const inspect = require('unist-util-inspect')

const res = unified()
  .use(markdown)
  .parse(vfile.readSync('example.md'))
console.log(inspect(res))
